import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function readOrEmpty(path) {
  try {
    return await readFile(new URL(path, import.meta.url), "utf8");
  } catch {
    return "";
  }
}

const staticMetadataExpectations = [
  {
    file: "./page.tsx",
    path: "/",
    title: "제로소싱 | MVP·앱·홈페이지 개발 외주 파트너",
    description:
      "MVP 개발 외주 전문 제로소싱. 핵심 기능만 담아 평균 4주 만에 출시·검증합니다. 앱·기업 홈페이지·강의·쇼핑몰까지, 기능별 정찰가로 투명하게. 무료 상담으로 시작하세요.",
  },
  {
    file: "./service/mvp/page.tsx",
    path: "/service/mvp",
    title: "제로소싱 | MVP 개발 외주, 평균 4주 출시",
    description:
      "제로소싱의 MVP 개발 외주는 검증되는 MVP를 평균 4주 만에 제작합니다. 예비창업패키지 등 정부지원금 집행이 가능하고, 기능별 정찰가로 견적이 투명합니다. MVP 개발 비용·기간·진행 방식을 안내합니다.",
  },
  {
    file: "./service/app/page.tsx",
    path: "/service/app",
    title: "제로소싱 | 하이브리드 앱 개발 (iOS·안드로이드)",
    description:
      "제로소싱의 하이브리드 앱 개발은 한 번 개발해 iOS·안드로이드에 동시 출시합니다. 푸시·결제 등 네이티브 기능 연동과 구글·애플 스토어 등록 대행 포함. 앱 개발 비용·기간을 안내합니다.",
  },
  {
    file: "./service/company-homepage/page.tsx",
    path: "/service/company-homepage",
    title: "제로소싱 | 기업 홈페이지 제작 (반응형·SEO)",
    description:
      "제로소싱의 기업 홈페이지 제작은 반응형과 네이버·구글·AI 검색 노출(SEO·GEO), 도메인·서버·보안까지 한 번에 제공합니다. 홈페이지 제작 비용·과정과 업종별 제작 사례를 확인하세요.",
  },
  {
    file: "./about/page.tsx",
    path: "/about",
    title: "제로소싱 | MVP 개발 외주 전문 팀 회사소개",
    description:
      "제로소싱은 목적에 맞는 가장 빠른 방법으로, 때로는 AI를 활용해 더 가볍게 MVP를 만드는 개발 외주 팀입니다. 부담은 덜고 출시는 앞당기는 제로소싱의 일하는 방식과 철학을 소개합니다.",
  },
  {
    file: "./blog/layout.tsx",
    path: "/blog",
    title: "제로소싱 블로그 | MVP·외주 개발 인사이트",
    description:
      "제로소싱 블로그에서 MVP 개발과 외주 개발을 더 잘하는 법을 나눕니다. 견적·비용 가이드부터 앱 개발, SEO·GEO, 정부지원사업 활용까지 현장에서 얻은 인사이트를 전합니다.",
  },
  {
    file: "./portfolio/layout.tsx",
    path: "/portfolio",
    title: "제로소싱 포트폴리오 | MVP·앱·홈페이지 제작 사례",
    description:
      "제로소싱 포트폴리오. MVP·하이브리드 앱·기업 홈페이지·인터넷 강의·온라인 쇼핑몰까지, 견적·기간·기능 등 실제 제작 사례를 확인하세요. 빠르게 검증하고 출시한 프로젝트를 모았습니다.",
  },
  {
    file: "./faq/layout.tsx",
    path: "/faq",
    title: "제로소싱 | 자주 묻는 질문(FAQ)",
    description:
      "제로소싱 자주 묻는 질문. MVP 개발 비용과 견적, 개발 기간, 노코드·AI 개발 방식, 하이브리드 앱, 기업 홈페이지 SEO·GEO, 출시 후 유지보수와 소유권까지 한눈에 정리했습니다.",
  },
  {
    file: "./contact/layout.tsx",
    path: "/contact",
    title: "제로소싱 | 문의접수",
    description:
      "제로소싱에 MVP·앱·홈페이지 개발을 문의하세요. 아이디어만 있어도 괜찮습니다. 남겨주시면 영업일 기준 하루 안에 연락드리고, 상담과 견적은 무료입니다. 기능별 정찰가로 투명하게 안내합니다.",
  },
  {
    file: "./term/page.tsx",
    path: "/term",
    title: "제로소싱 | 이용약관",
    description:
      "제로피가 제공하는 디지털 콘텐츠 거래 및 구독 플랫폼 서비스의 이용약관입니다.",
  },
  {
    file: "./privacy/page.tsx",
    path: "/privacy",
    title: "제로소싱 | 개인정보처리방침",
    description:
      "제로피가 수집·이용하는 개인정보의 항목, 처리 목적, 보유 기간 및 이용자 권리를 안내합니다.",
  },
];

test("the shared metadata helper owns the canonical domain and social image", async () => {
  const source = await readOrEmpty("./site-metadata.ts");

  assert.match(source, /export const SITE_URL = "https:\/\/www\.zerosourcing\.kr";/);
  assert.match(source, /export function createPageMetadata/);
  assert.match(source, /url: `\$\{SITE_URL\}\/og\.png`/);
  assert.match(source, /width: 1200/);
  assert.match(source, /height: 800/);
  assert.match(source, /card: "summary_large_image"/);
  assert.doesNotMatch(source, /zerosourcing\.com/);
});

test("the root layout supplies Korean defaults and Organization JSON-LD", async () => {
  const source = await readOrEmpty("./layout.tsx");

  assert.match(source, /metadataBase: new URL\(SITE_URL\)/);
  assert.match(source, /createPageMetadata/);
  assert.match(source, /organization-json-ld\.json/);
  assert.match(source, /type="application\/ld\+json"/);
  assert.match(source, /JSON\.stringify\(organizationJsonLd\)/);
  assert.match(source, /<html lang="ko">/);
  assert.doesNotMatch(source, /Create Next App|Generated by create next app/);
});

test("every static public route exports the approved metadata copy", async () => {
  for (const expectation of staticMetadataExpectations) {
    const source = await readOrEmpty(expectation.file);

    assert.match(source, /createPageMetadata\(\{/);
    assert.ok(
      source.includes(JSON.stringify(expectation.title)),
      expectation.file,
    );
    assert.ok(
      source.includes(JSON.stringify(expectation.description)),
      expectation.file,
    );
    assert.ok(source.includes(`path: ${JSON.stringify(expectation.path)}`));
  }
});

test("blog and portfolio details derive metadata from their route data", async () => {
  const [blog, portfolio, blogIndex, portfolioIndex] = await Promise.all([
    readOrEmpty("./blog/[slug]/page.tsx"),
    readOrEmpty("./portfolio/[slug]/page.tsx"),
    readOrEmpty("./blog/page.tsx"),
    readOrEmpty("./portfolio/page.tsx"),
  ]);

  assert.match(blog, /export async function generateMetadata/);
  assert.match(blog, /getPublishedBlogPost/);
  assert.match(blog, /title: `제로소싱 \| \$\{post\.title\}`/);
  assert.match(blog, /description: post\.seoDescription \|\| post\.summary/);
  assert.match(blog, /path: `\/blog\/\$\{post\.slug\}`/);
  assert.match(blog, /<ManagedContent/);
  assert.doesNotMatch(blog, /blog-posts|generateStaticParams/);

  assert.match(portfolio, /export async function generateMetadata/);
  assert.match(portfolio, /getPublishedPortfolio/);
  assert.match(portfolio, /title: `제로소싱 \| \$\{portfolio\.title\}`/);
  assert.match(
    portfolio,
    /description: portfolio\.seoDescription \|\| portfolio\.description/,
  );
  assert.match(portfolio, /path: `\/portfolio\/\$\{portfolio\.slug\}`/);
  assert.match(portfolio, /<ManagedContent/);
  assert.doesNotMatch(portfolio, /portfolio-items|generateStaticParams/);

  assert.match(blogIndex, /getPublishedBlogPosts/);
  assert.match(blogIndex, /selectBlogIndex/);
  assert.doesNotMatch(blogIndex, /blog-posts/);

  assert.match(portfolioIndex, /getPublishedPortfolios/);
  assert.match(portfolioIndex, /selectPortfolioIndex/);
  assert.doesNotMatch(portfolioIndex, /portfolio-items/);
});

test("robots and sitemap expose the canonical public routes", async () => {
  const [robots, sitemap] = await Promise.all([
    readOrEmpty("./robots.ts"),
    readOrEmpty("./sitemap.xml/route.ts"),
  ]);

  assert.match(robots, /sitemap: `\$\{SITE_URL\}\/sitemap\.xml`/);
  assert.match(robots, /host: SITE_URL/);
  assert.match(sitemap, /export const dynamic = "force-dynamic";/);
  assert.match(sitemap, /export async function GET/);
  assert.match(sitemap, /getPublishedBlogPosts/);
  assert.match(sitemap, /getPublishedPortfolios/);
  assert.match(sitemap, /post\.updatedAt/);
  assert.match(sitemap, /portfolio\.updatedAt/);
  assert.doesNotMatch(sitemap, /blog-posts|portfolio-items/);

  for (const path of staticMetadataExpectations.map((item) => item.path)) {
    assert.ok(sitemap.includes(JSON.stringify(path)), path);
  }
});
