export const metrics = [
  { label: "누적 프로젝트", value: "172건+", note: "2025년 9월 기준" },
  { label: "재의뢰율", value: "47.2%", note: "2025년 9월 기준" },
  { label: "평균 MVP 출시 기간", value: "4주", note: "기능 규모에 따라 변동" },
] as const;

export const categories = ["전체", "MVP", "어플리케이션", "기업 홈페이지"] as const;

export type Category = (typeof categories)[number];

export const portfolioItems = [
  {
    category: "기업 홈페이지",
    description: "인터넷 강의 홈페이지 제작 SaaS",
    duration: "소요기간 3주",
    slug: "classit",
    title: "클래스잇",
  },
  {
    category: "MVP",
    description: "초보 학습자를 위한 투두리스트 제공 플랫폼",
    duration: "소요기간 3주",
    slug: "todomall",
    title: "[MVP] 투두몰",
  },
  {
    category: "MVP",
    description: "공기업·사회적기업 채용 및 리뷰 플랫폼",
    duration: "소요기간 3주",
    slug: "gongsa-morakmorak",
    title: "[MVP] 공:사 모락모락",
  },
  {
    category: "어플리케이션",
    description: "시니어 행사 참여인원 모집 플랫폼",
    duration: "소요기간 3주",
    slug: "meetit-plus",
    title: "[MVP] 믿잇 플러스",
  },
  {
    category: "기업 홈페이지",
    description: "장례 견적 사전 조회 홈페이지",
    duration: "소요기간 3주",
    slug: "jangryedam",
    title: "장례담",
  },
  {
    category: "어플리케이션",
    description: "해외 불법 상품 차단 데이터 CRM",
    duration: "소요기간 3주",
    slug: "lipang",
    title: "리팡",
  },
  {
    category: "기업 홈페이지",
    description: "콘텐츠 운영형 기업 웹사이트",
    duration: "소요기간 3주",
    slug: "opus-house",
    title: "오퍼스하우스",
  },
  {
    category: "MVP",
    description: "로컬 커뮤니티 검증 플랫폼",
    duration: "소요기간 3주",
    slug: "my-plan-it",
    title: "[MVP] 마이플랜잇",
  },
  {
    category: "어플리케이션",
    description: "사용자 예약 및 알림 앱",
    duration: "소요기간 3주",
    slug: "relive-deal",
    title: "리라이브딜",
  },
] as const;

export const portfolioDetails = [
  {
    category: "기업 홈페이지",
    description: "인터넷 강의 홈페이지 제작 SaaS",
    estimate: "프로젝트별 협의",
    features: ["강의 콘텐츠", "회원 관리", "반응형 화면"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "classit",
    title: "클래스잇",
  },
  {
    category: "MVP 개발",
    description: "초보 학습자를 위한 투두리스트 제공 플랫폼",
    estimate: "프로젝트별 협의",
    features: ["할 일 관리", "학습 기록", "사용자 화면"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "todomall",
    title: "투두몰",
  },
  {
    category: "MVP 개발",
    description: "공기업·사회적기업 채용 및 리뷰 플랫폼",
    estimate: "프로젝트별 협의",
    features: ["채용 정보", "기업 리뷰", "검색·필터"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "gongsa-morakmorak",
    title: "공:사 모락모락",
  },
  {
    category: "MVP 개발",
    description: "시니어 활동 프로그램 홍보 및 참가자 모집 플랫폼",
    estimate: "298만 원(VAT포함)",
    features: ["활동 등록", "신청·참여", "선착순", "알림톡", "비회원 조회"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "도메인·서버"],
    slug: "meetit-plus",
    title: "믿잇 플러스(CJ제일제당 사내벤처)",
  },
  {
    category: "기업 홈페이지",
    description: "장례 견적 사전 조회 홈페이지",
    estimate: "프로젝트별 협의",
    features: ["견적 조회", "서비스 안내", "상담 연결"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "jangryedam",
    title: "장례담",
  },
  {
    category: "어플리케이션 개발",
    description: "해외 불법 상품 차단 데이터 CRM",
    estimate: "프로젝트별 협의",
    features: ["데이터 관리", "상품 모니터링", "업무 대시보드"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "앱 개발", "배포"],
    slug: "lipang",
    title: "리팡",
  },
  {
    category: "기업 홈페이지",
    description: "콘텐츠 운영형 기업 웹사이트",
    estimate: "프로젝트별 협의",
    features: ["콘텐츠 관리", "회사 소개", "반응형 화면"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "opus-house",
    title: "오퍼스하우스",
  },
  {
    category: "MVP 개발",
    description: "로컬 커뮤니티 검증 플랫폼",
    estimate: "프로젝트별 협의",
    features: ["커뮤니티", "지역 정보", "사용자 참여"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "웹 개발", "배포"],
    slug: "my-plan-it",
    title: "마이플랜잇",
  },
  {
    category: "어플리케이션 개발",
    description: "사용자 예약 및 알림 앱",
    estimate: "프로젝트별 협의",
    features: ["예약 관리", "푸시 알림", "사용자 화면"],
    period: "3주",
    scope: ["기획", "UX/UI 디자인", "앱 개발", "배포"],
    slug: "relive-deal",
    title: "리라이브딜",
  },
] as const;

export const featuredCase = portfolioDetails.find(
  (portfolio) => portfolio.slug === "meetit-plus",
)!;
